cortex/run.py
Importing log from feature types should fix a potential issue where a feature analysis crash could attempt to call an undefined function.
=> Fixed small issue to ensure feature crashes are logged correctly

cortex/feature_types.py, cortex/raw/accelerometer.py, cortex/run.py
Fixes an issue with getting quality metrics if timestamps are floats instead of ints.
=> casting timestamps to ints

cortex/secondary/entropy.py
Deleting the case where entropy is set to None if it is 0.
The only case where entropy would be 0 is when there is 1 significant location. If there are no significant locations, None is returned.
=> Updating entropy

cortex/feature_types.py
Data quality metrics were artificially inflated because the start and end time were set to the start and end of the raw data instead of the start and end of the window. Therefore, people with a few clusters of very dense data could have high frequencies even though averaged over time they had very few samples.
=> fixing quality metrics

cortex/secondary/data_quality.py
Switched the comparisons to use the built-in between() function for speed purposes.
=> using built in function

cortex/secondary/data_quality.py
If running data quality at a lower resolution (for example hourly) it is more efficient to pull individual data points from the API than loading all data. Thus, this implementation tries to find the balance between these two, setting a threshold of 150 "bins." We will continue to test to determine the optimal threshold, but this implementation should help speed up low resolution queries.
=> Update Data Quality

cortex/secondary/step_count.py
Catching an edge case where device type is unknown from lamp.analytics and iOS is assumed but the phone is Android (can tell from "com.google.android.gms" source).
=> Step count fix

cortex/secondary/entropy.py
Entropy had an error where 0 was returned instead of None when there was no data. This has been fixed.
=> Fixing entropy

cortex/raw/sleep.py, cortex/secondary/healthkit_sleep_duration.py, cortex/secondary/sleep_duration.py, cortex/secondary/survey_results.py
Adding "lamp.sleep" as a raw feature and healthkit sleep as a secondary feature. Pulls either "in_bed", "in_sleep", or "in_awake" durations. For an inital exploration, it seems that many users do not have sleep data and of those that do most have "in_bed" data.
=> adding healthkit sleep

cortex/primary/survey_scores.py, cortex/secondary/survey_results.py
Added a flag in survey_scoring that returns individual question scores as well as overall category scores. Essentially, the returned data will be a category, question (the same as the category for overall scores), and the score.
survey_results will still return the average for a category (or a question).
=> Adding question-wise scoring

cortex/feature_types.py, cortex/primary/game_level_scores.py, cortex/primary/survey_scores.py, cortex/raw/balloon_risk.py, cortex/raw/cats_and_dogs.py, cortex/raw/jewels_a.py, cortex/raw/jewels_b.py, cortex/raw/pop_the_bubbles.py, cortex/raw/spatial_span.py, cortex/secondary/game_results.py, cortex/secondary/survey_results.py, run_pylint.sh
Raw:
- Changed the structure so that raw data for games is simply what is returned from LAMP.ActivityEvent
- Added in all games: cats_and_dogs, balloon_risk, pop_the_bubbles, jewels_a, jewels_b, spatial_span
Primary
- Return scores for each level of each game played. Start timestamps are identical for all levels of the game, so these can be used to group by game if desired.
- Tap time is used as the score metric for cats_and_dogs, jewels_a, jewels_b, spatial_span
- Average pumps is the score metric for balloon_risk
- Average percent of no-go trials correct is the metric for pop_the_bubbles
- Of course, these metrics can be changed in the future if a better scoring metric is determined.
Secondary
- The secondary feature returns the average of the level scores for each game.
I will update …
=> Updating game scoring

cortex/secondary/step_count.py
In some of the past Android data, there is no "steps" field in lamp.steps data. This is for that edge case.
=> minor fix to step count

cortex/raw/survey.py
For some reason raw.survey had cache set to True. Caching should always default to false.
=> setting cache to false

cortex/feature_types.py, cortex/primary/significant_locations.py, cortex/primary/sleep_periods.py, cortex/raw/balloon_risk.py, cortex/raw/cats_and_dogs.py, cortex/raw/jewels_a.py, cortex/raw/jewels_b.py, cortex/raw/pop_the_bubbles.py, cortex/raw/screen_state.py, cortex/raw/sleep.py, cortex/raw/spatial_span.py, cortex/raw/steps.py, cortex/raw/survey.py, cortex/run.py, cortex/utils/db.py, cortex/utils/module_scheduler.py, cortex/utils/useful_functions.py, cortex/utils/useful_functions_misc.py, cortex/visualizations/correlation_functions.py, cortex/visualizations/data_quality.py
To make the code more streamlined, we have removed `LAMP.connect()` from everywhere except feature_types.py. As part of the import block, this code will be run every time that cortex is imported. Environment variables are required to be set in order to run cortex.
=> Removing lamp.connect

cortex/visualizations/correlation_functions.py
Importing seaborns and matplotlib with logging set to debug creates a huge amount of logs which aren't really cortex-related. This fixes the issue.
=> Remove unnecessary logs when importing

cortex/utils/useful_functions.py, cortex/visualizations/data_quality.py, cortex/visualizations/participant.py
This PR adds the following participant-level viz methods:
- `passive` - shows the amount of data collected hour-by-hour over a customizable period of time
- `active` - shows the number of activities collected day by day
- `cortex_tertiles` - allows visualization of (some) cortex data sorted into tertiles
In addition, a `set_graph` method is added to useful_functions to make it easier to set graphs on participants and make them visible across LAMP.
=> Adding participant visualization methods

cortex/feature_types.py, cortex/primary/screen_active.py, cortex/raw/calls.py, cortex/raw/device_state.py, cortex/raw/sleep.py, cortex/raw/sms.py, cortex/raw/steps.py, cortex/raw/survey.py, cortex/raw/telephony.py, cortex/raw/wifi.py, run_pylint.sh, tests/primary_feature_tests.py
Adding raw.device_state.
- screen_state is now deprecated. However, for backwards compatibility, pulling device_state data will also pull screen_state.
- Made raw.survey recursive.
- Added new tests for screen_active with new device_state data.
- Updated primary.screen_active to use the 'value' instead of 'state' key in accordance with device_state. Also removed the code to determine phone device type as the data should be the same across both now.
- Left code to check for activities to determine when is "on" versus "off" for backwards compatibility. This should be removed in later versions.
=> Adding device_state

cortex/secondary/data_quality.py, run_tests.sh, tests/secondary_feature_tests.py, tests/util_tests.py
Fixing some errors (mostly related to the new updates).
- data_quality.py had a typo which is now fixed
- removed extra imports from util_tests.py
- Updated run_tests.sh to work with the new version of coverage
- Updated step_count tests to be correct
There are still some warnings from running unittests. These can be resolved in a separate PR if applicable, but for reference: 
- Resource warning: unclosed SSL socket
- Exception ignored on calling ctypes callback function (File "/opt/conda/lib/python3.8/site-packages/threadpoolctl.py)
=> Fixing errors

cortex/visualizations/participant.py
This PR fixes a bug that did not allow activity IDs to be passed as part of a target array when making a visualization with the Cortex `visualization.participant.active` method. Activity names and specs were and should remain usable
=> Active data id fix

cortex/secondary/screen_unlock_duration.py, cortex/secondary/screen_unlocks.py, cortex/secondary/screen_wakes.py
Added three new secondary cortex functions to capture additional device_usage data from Apple sensorkit (screen wake count, screen unlock count, screen unlock duration).
=> Add device usage features

pyproject.toml
For fresh installs of cortex in python 3.12, a few people ran into issues with the requests dependency. Adding it in explicitly.
=> Add requests dependency
