BIDMCDigitalPsychiatry/LAMP-cortex

cortex/feature_types.py
Attachment get and set, not yet tested
=> Attachments

cortex/raw/accelerometer.py, cortex/raw/calls.py, cortex/raw/gps.py, cortex/raw/jewels_a.py, cortex/raw/jewels_b.py, cortex/raw/screen_state.py, cortex/raw/sms.py, cortex/raw/steps.py, cortex/raw/survey.py
Making sure we break the loops when start==end rather than getting stuck.  Also code formatting for all raw feature functions
=> format all raw and check duplicate end events

cortex/feature_types.py, cortex/raw/accelerometer.py, cortex/raw/gps.py
add support for local raw data cache
=> Raw pickles

cortex/feature_types.py, cortex/run.py
Missed a few bugs in the last pull request. Should be good to go
=> Advanced caching fix

cortex/run.py
=> Minor fixes for recursive generate_ids function

cortex/feature_types.py, cortex/secondary/stationary_proportion.py
`stationary_proportion` feature added; Empty array condition accounted for in secondary_feature decorator
=> Stationary proportion

cortex/primary/significant_locations.py
Added new method called 'mode' for computing significant locations
- can now choose between 'mode' and 'k_means'
- takes the most common latitude / longitude pairs as the significant locations
- latitude and longitude are rounded to 3 decimal places to compute mode
=> Siglocmode

cortex/secondary/active_duration.py
Fixing bug with active duration. Checking for duplicates in the wrong place.
=> fixing active duration

cortex/secondary/acc_energy.py
=> fixing error in acc_energy

cortex/run.py, cortex/secondary/entropy.py
Updating the run function.
- can pass raw, primary, and secondary features
- can specify parameters to pass to each function
- sets time to start / end at 9am if not specified
- allows you to pass a path to save the data
- allows you to pass a csv file containing participant ids and features to run
=> updating run

cortex/feature_types.py, cortex/secondary/sleep_duration.py
Fixing an issue where the _event variable was changing _body_new and causing attachments to be set improperly.
=> fixing attachments issue

cortex/feature_types.py
There is an issue where if attachments are empty an exception will be thrown. Added a fix for this.
=> fixing issue with empty attachments

cortex/feature_types.py, cortex/run.py, run_pylint.sh
Adding in mean / variance frequency for raw features and percent data over a threshold. Currently bins every 10 minutes to generate these estimates. Should be O(n), but we should make sure this does not affect runtime. 
Let me know your thoughts @ryan-hays @rydmel
=> adding quality metrics for raw features

cortex/raw/gyroscope.py
Added raw gyroscope and fixed accelerometer docstring
=> added raw gyroscope

cortex/secondary/trip_distance.py, cortex/secondary/trip_duration.py, run_pylint.sh
Changing the return type for trip_duration and trip_distance so that it matches the name of the feature.
=> changing return name

cortex/secondary/trip_distance.py, cortex/secondary/trip_duration.py
Added timestamps to trip duration and trip distance.
=> adding timestamp to trips

cortex/secondary/bluetooth_device_count.py, cortex/secondary/call_degree.py, cortex/secondary/call_duration.py, cortex/secondary/call_number.py, cortex/secondary/data_quality.py, cortex/secondary/entropy.py, cortex/secondary/hometime.py, cortex/secondary/screen_duration.py, cortex/secondary/sleep_duration.py, cortex/secondary/sms_number.py, cortex/secondary/trip_distance.py, cortex/secondary/trip_duration.py
Changing return value "data" to "value" for clarity.
=> chaning to value

cortex/run.py
Since caching now defaults to false, added a cache parameter to the run function to allow users to turn caching on.
=> adding caching to run

cortex/run.py, cortex/secondary/data_quality.py, cortex/secondary/entropy.py, cortex/secondary/hometime.py, cortex/secondary/screen_duration.py, cortex/secondary/sleep_duration.py, cortex/secondary/sms_number.py, cortex/secondary/step_count.py, cortex/secondary/trip_distance.py, cortex/secondary/trip_duration.py, run_pylint.sh, run_tests.sh, tests/secondary_feature_tests.py
Created a secondary feature for step count to work differently for iOS and Android. Added secondary tests as well.
=> Adding step count

cortex/feature_types.py, cortex/visualizations/data_quality.py, run_pylint.sh
Adding device_state / screen_state to cortex raw and data quality.
=> Updating to include device_state

cortex/primary/survey_scores.py, cortex/secondary/survey_results.py
Fixed an error in survey_results where "map_to" would not work properly. Also changed survey_results to produce averages for only one category of survey at a time so that it matches the secondary feature form of returning a "value" for each timestamp.
=> Fixing survey stuff

cortex/secondary/inactive_duration.py
Updated implementation of inactive_duration (secondary feature)
=> Add gap threshold

cortex/utils/useful_functions.py
I forgot to implement excluding certain tags when propagating activity changes in the previous branch. It is updated here.
=> updating excluded tags

cortex/primary/game_level_scores.py, cortex/primary/significant_locations.py, cortex/primary/survey_scores.py, cortex/primary/trips.py, cortex/raw/survey.py, cortex/raw/telephony.py, cortex/run.py, cortex/utils/db.py, cortex/visualizations/data_quality.py, run_pylint.sh
Adding the telephony sensor as a raw feature. Also cleaned up style in some files namely utils/db.py and raw/survey.py,
=> Add telephony sensor

cortex/utils/useful_functions.py, cortex/visualizations/data_quality.py
Adding a new visualization function for "percent completion" of activity counts.
=> Adding new viz function

cortex/secondary/step_count.py, tests/secondary_feature_tests.py
Updating step_count and the step_count unit tests to work with the new data format (unified between iOS and Android).
=> Update step count

cortex/secondary/call_duration.py, cortex/secondary/call_number.py, run_pylint.sh, run_tests.sh, tests/secondary_feature_tests.py
Update to call_duration, and added to tests and pylint.
=> updates to call_duration

cortex/run.py
Changed min() to max() such that all data is captured.
=> changes to cortex run

cortex/raw/ambient_light.py, cortex/raw/device_usage.py, cortex/raw/messages_usage.py, cortex/raw/phone_usage.py, cortex/raw/visits.py
Integrating sensorkit sensors as raw features
=> integrating raw sensorkit features

cortex/secondary/call_degree.py, run_tests.sh, tests/secondary_feature_tests.py
Update to call degree for telephony
=> call degree update

cortex/visualizations/data_quality.py
Updating data quality column names.
=> updated d quality

cortex/secondary/app_time.py
Adding new secondary feature to get total time spent using each app category.
=> apptime updates

cortex/feature_types.py, cortex/raw/dcog.py, run_pylint.sh
=> D-Cog raw data functionality

cortex/feature_types.py, cortex/raw/digit_span.py, cortex/raw/fragmented_letters.py, cortex/raw/funny_memory.py, cortex/raw/trails_b.py, cortex/raw/voice_survey.py, run_pylint.sh
Added cortex raw data functions for:
voice_survey
trails_b
funny_memory
fragmented_letters
digit_span
=> Added cortex raw data functions for new games

cortex/raw/digit_span.py, cortex/raw/funny_memory.py, cortex/raw/trails_b.py
Adding new docstrings to the cortex raw data functions for the following games
- Funny Memory
- Trails B
- Digit Span
The following games are not yet functional enough to provided detailed data structure information yet
- Speech Recognition
- Fragmented Letters
=> Added Docstrings for working new games
